#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'json'
require 'open3'
require 'pathname'

repo_root = Pathname.new(__dir__).join('../..').realpath
pods_project = repo_root.join('ios/Pods/Pods.xcodeproj')
pods_project_file = pods_project.join('project.pbxproj')
flutter_packages_root = repo_root.join('ios/Flutter/ephemeral/Packages')
generated_plugin_package = flutter_packages_root.join('FlutterGeneratedPluginSwiftPackage')
target_map = repo_root.join('ios/Flutter/ephemeral/ForkIdentityDependencies.xcconfig')

unless ARGV.empty?
  warn 'Usage: scripts/fork/prepare_ios_testflight.rb'
  exit 1
end

unless pods_project_file.file?
  warn "Missing generated CocoaPods project: #{pods_project_file}"
  warn 'Run pod install before this helper.'
  exit 1
end

deployment_pattern = /IPHONEOS_DEPLOYMENT_TARGET = [^;]+;/
project_contents = pods_project_file.read
deployment_setting_count = project_contents.scan(deployment_pattern).length
if deployment_setting_count.zero?
  warn "No iOS deployment settings found in #{pods_project_file}"
  exit 1
end

updated_project_contents = project_contents.gsub(deployment_pattern, 'IPHONEOS_DEPLOYMENT_TARGET = 15.0;')
if updated_project_contents != project_contents
  temporary_project_file = Pathname.new("#{pods_project_file}.tmp-#{Process.pid}")
  temporary_project_file.write(updated_project_contents)
  temporary_project_file.rename(pods_project_file)
end

stdout, stderr, status = Open3.capture3(
  'xcodebuild',
  '-project',
  pods_project.to_s,
  '-list',
  '-json',
)
unless status.success?
  warn stderr
  warn 'Could not enumerate generated CocoaPods targets.'
  exit 1
end

pod_targets = JSON.parse(stdout).dig('project', 'targets')
unless pod_targets.is_a?(Array) && !pod_targets.empty?
  warn 'The generated CocoaPods project did not report any targets.'
  exit 1
end

def package_build_targets(manifest)
  stdout, stderr, status = Open3.capture3(
    'xcrun',
    'swift',
    'package',
    '--package-path',
    manifest.dirname.to_s,
    'dump-package',
  )
  unless status.success?
    warn stderr
    warn "Could not enumerate generated Swift package targets from #{manifest}."
    exit 1
  end

  package = JSON.parse(stdout)
  target_names = package.fetch('targets', []).map do |target|
    name = target['name']
    name if name.is_a?(String) && !name.empty?
  end.compact
  package_name = package['name']
  product_names = package.fetch('products', []).map { |product| product['name'] }.grep(String).reject(&:empty?)
  product_build_targets = product_names.flat_map do |product_name|
    names = [product_name, "#{product_name}-product"]
    names << "#{package_name}_#{product_name}" if package_name.is_a?(String) && !package_name.empty?
    names
  end
  (target_names + product_build_targets).uniq
rescue JSON::ParserError => error
  warn "Could not parse generated Swift package metadata from #{manifest}: #{error.message}"
  exit 1
end

swift_package_manifests = []
generated_manifest = generated_plugin_package.join('Package.swift')
if generated_manifest.file?
  swift_package_manifests << generated_manifest
  generated_dependencies = flutter_packages_root.join('.packages')
  if generated_dependencies.directory?
    generated_dependencies.children.sort.each do |dependency|
      manifest = dependency.join('Package.swift')
      swift_package_manifests << manifest if manifest.file?
    end
  end
end
swift_package_targets = swift_package_manifests.flat_map { |manifest| package_build_targets(manifest) }.uniq

def c99_identifier(value)
  identifier = value.gsub(/[^A-Za-z0-9_]/, '_')
  identifier = "_#{identifier}" if identifier.match?(/\A[0-9]/)
  identifier
end

dependency_targets = (pod_targets + swift_package_targets).uniq
target_keys = dependency_targets.map { |target| c99_identifier(target) }.uniq

target_map_lines = [
  '// Generated by scripts/fork/prepare_ios_testflight.rb. Do not commit.',
  '',
]
target_keys.sort.each do |target_key|
  target_map_lines << "CHALDEA_IOS_BUNDLE_ID_#{target_key} = org.cocoapods.$(PRODUCT_NAME:rfc1034identifier)"
  target_map_lines << "CHALDEA_IOS_ENTITLEMENTS_#{target_key} ="
  target_map_lines << "CHALDEA_IOS_DEPLOYMENT_TARGET_#{target_key} = 15.0"
end

FileUtils.mkdir_p(target_map.dirname)
temporary_target_map = Pathname.new("#{target_map}.tmp-#{Process.pid}")
temporary_target_map.write("#{target_map_lines.join("\n")}\n")
temporary_target_map.rename(target_map)

puts 'status=prepared'
puts "deployment_setting_count=#{deployment_setting_count}"
puts "pod_target_count=#{pod_targets.length}"
puts "swift_package_target_count=#{swift_package_targets.length}"
puts "dependency_target_count=#{dependency_targets.length}"
puts "dependency_target_key_count=#{target_keys.length}"
puts "target_map=#{target_map}"
