#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'json'
require 'open3'
require 'pathname'

repo_root = Pathname.new(__dir__).join('../..').realpath
pods_project = repo_root.join('ios/Pods/Pods.xcodeproj')
pods_project_file = pods_project.join('project.pbxproj')
target_map = repo_root.join('ios/Flutter/ephemeral/ForkIdentityPods.xcconfig')

unless ARGV.empty?
  warn 'Usage: scripts/fork/prepare_ios_testflight.rb'
  exit 1
end

unless pods_project_file.file?
  warn "Missing generated CocoaPods project: #{pods_project_file}"
  warn 'Run pod install before this helper.'
  exit 1
end

deployment_pattern = /IPHONEOS_DEPLOYMENT_TARGET = [^;]+;/
project_contents = pods_project_file.read
deployment_setting_count = project_contents.scan(deployment_pattern).length
if deployment_setting_count.zero?
  warn "No iOS deployment settings found in #{pods_project_file}"
  exit 1
end

updated_project_contents = project_contents.gsub(deployment_pattern, 'IPHONEOS_DEPLOYMENT_TARGET = 15.0;')
if updated_project_contents != project_contents
  temporary_project_file = Pathname.new("#{pods_project_file}.tmp-#{Process.pid}")
  temporary_project_file.write(updated_project_contents)
  temporary_project_file.rename(pods_project_file)
end

stdout, stderr, status = Open3.capture3(
  'xcodebuild',
  '-project',
  pods_project.to_s,
  '-list',
  '-json',
)
unless status.success?
  warn stderr
  warn 'Could not enumerate generated CocoaPods targets.'
  exit 1
end

targets = JSON.parse(stdout).dig('project', 'targets')
unless targets.is_a?(Array) && !targets.empty?
  warn 'The generated CocoaPods project did not report any targets.'
  exit 1
end

def c99_identifier(value)
  identifier = value.gsub(/[^A-Za-z0-9_]/, '_')
  identifier = "_#{identifier}" if identifier.match?(/\A[0-9]/)
  identifier
end

target_keys = targets.to_h { |target| [target, c99_identifier(target)] }
duplicate_keys = target_keys.values.group_by(&:itself).select { |_key, values| values.length > 1 }.keys
unless duplicate_keys.empty?
  warn "CocoaPods target names collide after xcconfig normalization: #{duplicate_keys.join(', ')}"
  exit 1
end

target_map_lines = [
  '// Generated by scripts/fork/prepare_ios_testflight.rb. Do not commit.',
  '',
]
target_keys.sort_by { |target, _target_key| target }.each do |_target, target_key|
  target_map_lines << "CHALDEA_IOS_BUNDLE_ID_#{target_key} = org.cocoapods.$(PRODUCT_NAME:rfc1034identifier)"
  target_map_lines << "CHALDEA_IOS_ENTITLEMENTS_#{target_key} ="
  target_map_lines << "CHALDEA_IOS_DEPLOYMENT_TARGET_#{target_key} = 15.0"
end

FileUtils.mkdir_p(target_map.dirname)
temporary_target_map = Pathname.new("#{target_map}.tmp-#{Process.pid}")
temporary_target_map.write("#{target_map_lines.join("\n")}\n")
temporary_target_map.rename(target_map)

puts 'status=prepared'
puts "deployment_setting_count=#{deployment_setting_count}"
puts "pod_target_count=#{targets.length}"
puts "target_map=#{target_map}"
